all:
	gs -sDEVICE=pdfwrite -sPAPERSIZE=letter -sOutputFile="2013-09-26-antonio-feed-support-box-control-v1_0-gerber.pdf" -c "<< /PageSize [792 612]  >> setpagedevice" -c "<</PageOffset [160 150]>> setpagedevice" -dAutoRotatePages=/None -dEPSFitPage -dPDFSETTINGS=/prepress -dNOPAUSE -dBATCH  \
2013-09-26-antonio-feed-support-box-control-v1_0-silk.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-top-bottom.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-top.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-middle-top.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-middle-bottom.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-bottom.ps 
