all:
	gs -sDEVICE=pdfwrite -sPAPERSIZE=letter -sOutputFile="2013-09-26-antonio-feed-support-box-control-v1_0-layout.pdf" -dNOPAUSE -dBATCH  \
2013-09-26-antonio-feed-support-box-control-v1_0-top-bottom.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-top-middle.ps \
2013-09-26-antonio-feed-support-box-control-v1_0-bottom-middle.ps
